version: '3'
services:
  api:
    container_name: users-api
    build: .
    ports: 
      - "8080:8080"
    restart: on-failure
    volumes:
      - .:/usr/src/app/
    depends_on:
      - postgres        
    networks:
      - users-network
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres_db_users
    environment:
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=users
      - DATABASE_HOST=postgres
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - users-network
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_users
    environment:
      PGADMIN_DEFAULT_EMAIL: bhuvanaccs@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    ports:
      - "5050:80"
    networks:
      - users-network
    restart: unless-stopped

volumes:
  database_postgres:                  

networks:
  users-network:
    driver: bridge